apply plugin: 'com.android.application'
android {
    namespace 'com.lingkar.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.lingkar.app"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}

// Force Kotlin version untuk hindari duplicate class
configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
    }
}
